### ISSUE TITLE
AttributeError: 'generator' object has no attribute 'choices' in ai.py

### ISSUE THREAD

**Issue by shuxinjin** [SkywalkerDarren/chatWeb#13]
Not familar with your codes, report error as below:
------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\py39\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\ProgramData\Anaconda3\envs\py39\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\ProgramData\Anaconda3\envs\py39\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\ProgramData\Anaconda3\envs\py39\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\ProgramData\Anaconda3\envs\py39\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\ProgramData\Anaconda3\envs\py39\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\coding\notNowUsing\nlp2000\News_nltk\Example_test\OpenaiFinancialReports\chatWeb\webui.py", line 130, in respond
    kw = self.ai.get_keywords(message)
  File "D:\coding\notNowUsing\nlp2000\News_nltk\Example_test\OpenaiFinancialReports\chatWeb\ai.py", line 86, in get_keywords
    result = self._chat_stream([
  File "D:\coding\notNowUsing\nlp2000\News_nltk\Example_test\OpenaiFinancialReports\chatWeb\ai.py", line 47, in _chat_stream
    print(response.choices[0].message.content.strip())
AttributeError: 'generator' object has no attribute 'choices'

**Comment by SkywalkerDarren** [comment]
Could you please provide your `config.json` configuration file without the key and the steps to reproduce the issue?

**Comment by shuxinjin** [comment]
Yes,please , thank you for your helping
------------------
{
  "open_ai_key": "sk-T66KPXmjNyx1vhV9Su",
  "temperature": 0.1,
  "language": "English",
  "open_ai_chat_model": "gpt-3.5-turbo",
  "use_stream": true,
  "use_postgres": false,
  "index_path": "./temp",
  "postgres_url": "postgresql://localhost:5432/mydb",
  "mode": "webui",
  "api_port": 9531,
  "api_host": "localhost",
  "webui_port": 7002
}

**Comment by SkywalkerDarren** [comment]
Thank you for raising the issue. The problem should have been fixed correctly. However, currently, the output for chat in the web UI mode does not yet support the stream mode.
